### ISSUE TITLE
SDTconvert should leave alone the original fits files directory.

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#154]
Launching SDTconvert with the following command:
SDTconvert -f classfits sardaraData/20181210/20181210-232201-24-18-W3OH/
results in the following error:

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: 'tmp_0.2831684002839501' -> 'sardaraData/20181210/20181210-232201-24-18-W3OH_classfits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/SDTconvert", line 19, in <module>
    load_entry_point('srttools==0.6.dev1249', 'console_scripts', 'SDTconvert')()
  File "/usr/lib/python3.6/site-packages/srttools-0.6.dev1249-py3.6.egg/srttools/convert.py", line 242, in main_convert
    launch_classfits_creator(fname, args.format, test=args.test)
  File "/usr/lib/python3.6/site-packages/srttools-0.6.dev1249-py3.6.egg/srttools/convert.py", line 141, in launch_classfits_creator
    shutil.move(random_name, outname)
  File "/usr/lib64/python3.6/shutil.py", line 555, in move
    symlinks=True)
  File "/usr/lib64/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: 'sardaraData/20181210/20181210-232201-24-18-W3OH_classfits'`

This happens because SDTconvert tries to write/create a directory alongside the one the user wishes to convert, but on SRT machines, data are accessible from a read-only filesystem for security reasons. I believe that SDTconvert's behavior should be changed, it should only operate/write inside the directory in which it gets executed.

**Comment by giuseppe-carboni** [comment]
Fixed with #159. Closing.
