### ISSUE TITLE
Header missing END card

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#210]
Some fits files processing get aborted with the following error.

2021-04-29 22:55:41 - Header missing END card. 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1103, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 38, in astropy.io.fits._utils.parse_header
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/monitor/monitor.py", line 220, in _process
    if main_preprocess(pp_args):
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/imager.py", line 1973, in main_preprocess
    nosave=args.nosave,
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/scan.py", line 959, in __init__
    table = read_data(data)
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/io.py", line 1005, in read_data
    return read_data_fitszilla(fname)
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/io.py", line 478, in read_data_fitszilla
    retval = _read_data_fitszilla(lchdulist)
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/io.py", line 568, in _read_data_fitszilla
    is_new_fitszilla = np.any(["coord" in i.name.lower() for i in lchdulist])
  File "/usr/lib/python3.6/site-packages/srttools-0.7.dev3+gb6649bb-py3.6.egg/srttools/io.py", line 568, in <listcomp>
    is_new_fitszilla = np.any(["coord" in i.name.lower() for i in lchdulist])
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 254, in __iter__
    yield self[idx]
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 307, in __getitem__
    self._positive_index_of(key))
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1105, in _try_while_unread_hdus
    if self._read_next_hdu():
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1146, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 327, in readfrom
    **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 414, in _readfrom_internal
    endcard=not ignore_missing_end)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 514, in fromfile
    padding)[1]
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 596, in _from_blocks
    raise OSError('Header missing END card.')

**Comment by matteobachetti** [comment]
This looks like the analyzed FITS files are *not* FITS at all. Could you send me the offending files or some more debugging information?

**Comment by giuseppe-carboni** [comment]
Ok, after an analysis of the file, this seems like a false alarm. Closing.
